services:
  - type: web
    name: boyu
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py $PORT
    healthCheckPath: /api/health
    autoDeploy: true
